export const c = {
  accentGreen:   '#166534',
  primaryText:   '#1c1917',
  secondaryText: '#78716c',
  mutedText:     '#a8a29e',
  border:        '#e7e5e4',
  subtleBg:      '#f5f5f4',
  stoneBg:       '#fafaf9',
  white:         '#ffffff',
  greenPositive: '#15803d',
  successBg:     '#f0fdf4',
  successBorder: '#bbf7d0',
} as const

export const shared = {
  mainSection: {
    padding: '32px 40px',
  },
  heading: {
    fontSize: '26px' as const,
    fontWeight: '600' as const,
    color: '#1c1917',
    margin: '0 0 12px',
    letterSpacing: '-0.4px',
    lineHeight: '1.2',
  },
  bodyText: {
    fontSize: '15px' as const,
    color: '#78716c',
    margin: '0 0 20px',
    lineHeight: '1.6',
  },
  orderId: {
    fontFamily: 'monospace',
    backgroundColor: '#f5f5f4',
    padding: '2px 6px',
    borderRadius: '4px',
    color: '#1c1917',
    fontSize: '14px' as const,
  },
  ctaButton: {
    display: 'inline-block' as const,
    backgroundColor: '#1c1917',
    color: '#ffffff',
    padding: '12px 28px',
    borderRadius: '8px',
    textDecoration: 'none' as const,
    fontSize: '14px' as const,
    fontWeight: '500' as const,
    letterSpacing: '0.2px',
  },
  tableHr: {
    borderTop: '1px solid #e7e5e4',
    margin: '0',
  },
  colProduct: { width: '55%' },
  colSku:     { width: '25%' },
  colPrice:   { width: '20%' },
  tableHeaderCell: {
    fontSize: '11px' as const,
    fontWeight: '600' as const,
    color: '#a8a29e',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.6px',
    padding: '12px 0',
    margin: '0',
  },
  cellText: {
    fontSize: '14px' as const,
    color: '#1c1917',
    padding: '10px 0',
    margin: '0',
    lineHeight: '1.4',
  },
  cellMuted: {
    fontSize: '13px' as const,
    color: '#78716c',
    padding: '10px 0',
    margin: '0',
  },
  totalLabel: {
    fontSize: '15px' as const,
    fontWeight: '600' as const,
    color: '#1c1917',
    padding: '12px 0',
    margin: '0',
  },
  discountLabel: {
    fontSize: '14px' as const,
    color: '#15803d',
    padding: '10px 0',
    margin: '0',
    fontWeight: '500' as const,
  },
}
